teste ASP/Teste botão ASP/Botão asp/Models/ErrorViewModel.cs
namespace Botão_asp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

teste ASP/Teste botão ASP/Botão asp/Controllers/HomeController.cs
using Botão_asp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Botão_asp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

teste ASP/Teste botão ASP/Botão asp/Controllers/TestePaginaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Botão_asp.Controllers
{
    public class TestePaginaController : Controller
    {
        public IActionResult Index(string email)
        {
            return View();
        }
    }
}

teste ASP/Teste botão ASP/Botão asp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="Titulo A Pequena ">A Pequena Sereia</h1>
    <p> Não tem conta? <a href="@Url.Action("Index", "TestePagina")">Clique aqui para criar uma conta</a>.</p>
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>

<img src=" https://br.web.img2.acsta.net/pictures/17/07/10/17/01/183081.jpg" />
@*<button type="submit">Clique aqui para assistir</button>*@
@*<a href="https://drive.google.com/file/d/1h7UppmL8o0EiustLV9JtSbSmRr2iS8Eb/view?usp=drivesdk">*@
  @*<button class="A pequena sereia botao"> Clique aqui para assistir</button> *@


@*</a>*@
@*<button class="A pequena sereia botao"> *@
    @*<a href="https://drive.google.com/file/d/1h7UppmL8o0EiustLV9JtSbSmRr2iS8Eb/view?usp=drivesdk">Clique aqui para assistir</a>*@
@*</button>*@
<a class="btn btn-primary" href="https://drive.google.com/file/d/1h7UppmL8o0EiustLV9JtSbSmRr2iS8Eb/view?usp=drivesdk">Clique aqui para assistir</a>

teste ASP/Teste botão ASP/Botão asp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Filmes.Com</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Botão_asp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Filmes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Botão_asp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

teste ASP/Teste botão ASP/Botão asp/Views/TestePagina/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*<form asp-action="">*@

@*</form>*@
<h1>Criar conta</h1>
<p> Email:</p>
<input type="text" class="Email" placeholder="Insira seu e-mail" /> 
<br /> 
<br />
<p>Senha:</p>
<input type="password" class="Senha" placeholder="Insira a senha" />
<br />
<br />
<a href="https://drive.google.com/file/d/1h7UppmL8o0EiustLV9JtSbSmRr2iS8Eb/view?usp=drivesdk" class=" Botao btn btn-primary"> Confirmar</a>

<script>

</script>