TesteASP/TesteASP/Models/Ben10.cs
namespace TesteASP.Models
{
    public class Ben10
    {
      public string episodio {get;set;} //
      public int id_numero  {get;set;}
    }
}

TesteASP/TesteASP/Models/Conexao.cs
using System.Data.SqlClient;
using System.Data.SqlTypes;

namespace TesteASP.Models
{
    public class Conexao
    {
        private static SqlConnection Banco;
        public static SqlConnection GetConnection()
        {
            if (Banco == null)
            {
                Banco = new SqlConnection(@"Data Source=DESKTOP-5A62GND\SQLEXPRESS;Initial Catalog=Ben10;Integrated Security=True");
            }
            return Banco;
        }
    }
}

TesteASP/TesteASP/Models/ErrorViewModel.cs
namespace TesteASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TesteASP/TesteASP/Controllers/Ben10Controller.cs
using Microsoft.AspNetCore.Mvc;
using TesteASP.DAL;
using TesteASP.Models;

namespace TesteASP.Controllers
{
    public class Ben10Controller : Controller
    {
        public IActionResult Index()
        {
            Ben10DAL episodios = new Ben10DAL();
            ViewBag.ListaEpisodios = episodios.getTodosEpisodios(); 
            return View();
        }
      
    }
}

TesteASP/TesteASP/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TesteASP.Models;

namespace TesteASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TesteASP/TesteASP/Views/Ben10/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
  </div>
<div id="divtabela">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">"Episódio"</th>
                <th scope="col">"Título"</th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var item in @ViewBag.ListaEpisodios)
            {
                <tr>
                    <td>@item.episodio</td>
                    <td>@item.id_numero </td>
                   
                </tr>
            }
        </tbody>
    </table>
</div>
<div>

TesteASP/TesteASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Enciclopédia BEN 10</h1>
    <br>
    <p> Site feito para os fans do desenho Ben 10, contendo todas as informações sobre os episódios e omnitrix</p>
    <img src= https://m.media-amazon.com/images/M/MV5BZjg2ZjViMTktNWQ1Yy00ODZiLWE1OTgtNDY3MjI0OGUyNjNhXkEyXkFqcGdeQXVyNTk4NDI4NTE@._V1_FMjpg_UX1000_.jpg/>
   

    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TesteASP/TesteASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TesteASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TesteASP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TesteASP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ben10" asp-action="Index">Episodios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TesteASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>